apiVersion: apps/v1
kind: Deployment
metadata:
  name: shaker-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shaker-dashboard
  template:
    metadata:
      labels:
        app: shaker-dashboard
    spec:
      containers:
      - name: shaker-dashboard
        image: <your-container-registry>/shaker-dashboard:<tag>
        ports:
        - containerPort: 8501
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: shaker-dashboard-service
spec:
  type: LoadBalancer
  selector:
    app: shaker-dashboard
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8501
